import { StyleSheet } from 'react-native'
import { colors, radius, spacing } from '@/shared/ui/tokens'

const { brand, neutral } = colors

export const styles = StyleSheet.create({
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: spacing[5],
    paddingVertical: spacing[3],
  },
  greeting: { fontSize: 22, fontWeight: '800', color: neutral[900] },
  subtitle: { fontSize: 14, color: neutral[500], marginTop: 2 },
  hero: {
    marginHorizontal: spacing[5],
    marginTop: spacing[2],
    height: 220,
    borderRadius: radius.hero,
    overflow: 'hidden',
  },
  heroScrim: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0,0,0,0.35)',
  },
  heroContent: {
    flex: 1,
    padding: spacing[5],
    justifyContent: 'flex-end',
  },
  heroBadge: {
    alignSelf: 'flex-start',
    backgroundColor: brand.coral,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: radius.pill,
    marginBottom: spacing[2],
  },
  heroBadgeLabel: { color: neutral[0], fontSize: 11, fontWeight: '600' },
  heroTitle: { fontSize: 24, fontWeight: '800', color: neutral[0] },
  heroBody: { fontSize: 13, color: 'rgba(255,255,255,0.8)', marginTop: 4, marginBottom: spacing[3] },
  heroActions: { flexDirection: 'row', gap: spacing[2] },
  heroBtn: {
    flex: 1,
    height: 44,
    borderRadius: 12,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.25)',
  },
  heroBtnLabel: { color: neutral[0], fontSize: 14, fontWeight: '600' },
  preset: {
    paddingHorizontal: spacing[4],
    paddingVertical: 10,
    borderRadius: radius.compact,
  },
  presetGlass: {
    backgroundColor: 'rgba(255,255,255,0.78)',
    borderWidth: 1,
    borderColor: neutral[100],
  },
  presetLabel: { fontSize: 13, fontWeight: '600' },
  sectionTitle: { fontSize: 17, fontWeight: '700', color: neutral[900], marginBottom: spacing[3] },
  skeletonCard: { height: 96, flexDirection: 'row', overflow: 'hidden' },
  skeletonThumb: { width: 112, backgroundColor: neutral[100] },
  skeletonLine: { height: 12, borderRadius: 6, backgroundColor: neutral[100] },
  stateCard: { padding: spacing[6], alignItems: 'center' },
  stateEmoji: { fontSize: 36, marginBottom: spacing[3] },
  stateTitle: { fontSize: 15, fontWeight: '700', color: neutral[900], textAlign: 'center' },
  stateBody: { fontSize: 13, color: neutral[500], marginTop: 4, textAlign: 'center' },
  recoverBtn: {
    height: 44,
    borderRadius: 12,
    backgroundColor: neutral[50],
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: spacing[3],
  },
  recoverOutline: {
    backgroundColor: 'transparent',
    borderWidth: 1,
    borderColor: neutral[100],
  },
  recoverLabel: { fontSize: 14, fontWeight: '600', color: neutral[900] },
  planCard: { flexDirection: 'row', overflow: 'hidden' },
  planThumb: { width: 112, height: 96 },
  planTitle: { fontSize: 14, fontWeight: '700', color: neutral[900] },
  planMeta: { flexDirection: 'row', alignItems: 'center', gap: 4, marginTop: 4 },
  planMetaLabel: { fontSize: 12, color: neutral[500] },
  planTags: { flexDirection: 'row', flexWrap: 'wrap', gap: 6, marginTop: spacing[2], alignItems: 'center' },
  planBudget: { fontSize: 11, fontWeight: '600', color: brand.coral },
})
