import { StyleSheet } from 'react-native'

import { colors, glassFx, radius, spacing, overlay } from '@/shared/ui/tokens'

const { brand, neutral } = colors

export const styles = StyleSheet.create({
  searchRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing[2],
    paddingHorizontal: spacing[5],
    marginBottom: spacing[3],
  },
  input: {
    flex: 1,
    height: 48,
    borderRadius: radius.compact,
    backgroundColor: glassFx.chip,
    borderWidth: 1,
    borderColor: neutral[100],
    paddingHorizontal: spacing[4],
    fontSize: 14,
    color: neutral[900],
  },
  filterRow: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing[2], paddingHorizontal: spacing[5], paddingBottom: spacing[2] },
  filterToggle: {
    width: 48,
    height: 48,
    borderRadius: radius.compact,
    backgroundColor: glassFx.chip,
    borderWidth: 1,
    borderColor: neutral[100],
    alignItems: 'center',
    justifyContent: 'center',
  },
  filterToggleActive: { borderColor: brand.coral },
  filterToggleIcon: { fontSize: 18 },
  filterCountBadge: {
    position: 'absolute',
    top: -4,
    right: -4,
    minWidth: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: brand.coral,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 4,
  },
  filterCountLabel: { fontSize: 11, fontWeight: '700', color: neutral[0] },
  fab: {
    position: 'absolute',
    right: spacing[5],
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: brand.coral,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: brand.coral,
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.35,
    shadowRadius: 20,
    elevation: 8,
  },
  fabIcon: { fontSize: 26, fontWeight: '700', color: neutral[0], lineHeight: 30 },
  sheetInput: {
    height: 46,
    borderRadius: radius.compact,
    backgroundColor: neutral[50],
    borderWidth: 1,
    borderColor: neutral[100],
    paddingHorizontal: spacing[4],
    fontSize: 14,
    color: neutral[900],
  },
  priceRow: { flexDirection: 'row', alignItems: 'center', gap: spacing[2] },
  priceInput: { flex: 1 },
  priceDash: { fontSize: 16, color: neutral[500] },
  modalRoot: { flex: 1, justifyContent: 'flex-end' },
  backdrop: { ...StyleSheet.absoluteFillObject, backgroundColor: overlay.backdrop },
  sheet: {
    backgroundColor: glassFx.sheet,
    borderTopLeftRadius: radius.sheet,
    borderTopRightRadius: radius.sheet,
    paddingHorizontal: spacing[5],
    paddingTop: spacing[5],
  },
  handle: {
    width: 40,
    height: 4,
    borderRadius: 2,
    backgroundColor: neutral[100],
    alignSelf: 'center',
    marginBottom: spacing[4],
  },
  sheetTitle: { fontSize: 17, fontWeight: '800', color: neutral[900], marginBottom: spacing[2] },
  sheetSection: { fontSize: 13, fontWeight: '700', color: neutral[500], marginTop: spacing[3], marginBottom: spacing[2] },
  sheetOptionRow: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing[2] },
  sheetOption: {
    paddingHorizontal: 12,
    paddingVertical: 9,
    borderRadius: radius.compact,
    backgroundColor: neutral[50],
  },
  sheetOptionActive: { backgroundColor: brand.coral },
  sheetOptionLabel: { fontSize: 13, fontWeight: '600', color: neutral[700] },
  sheetOptionLabelActive: { color: neutral[0] },
  sheetApply: { marginTop: spacing[5] },
  sheetClear: { alignItems: 'center', paddingVertical: spacing[3] },
  sheetClearLabel: { fontSize: 14, fontWeight: '500', color: neutral[500] },
  filterBtn: {
    paddingHorizontal: spacing[4],
    paddingVertical: 8,
    borderRadius: radius.compact,
    backgroundColor: glassFx.chip,
    borderWidth: 1,
    borderColor: neutral[100],
  },
  filterBtnActive: { backgroundColor: neutral[900], borderColor: neutral[900] },
  filterLabel: { fontSize: 13, fontWeight: '600', color: neutral[500] },
  filterLabelActive: { color: neutral[0] },
  card: { flexDirection: 'row', overflow: 'hidden', marginBottom: spacing[3] },
  thumb: { width: 96, alignSelf: 'stretch', minHeight: 96 },
  cardBody: { flex: 1, padding: spacing[3] },
  cardHeader: { flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between', gap: spacing[2] },
  title: { fontSize: 14, fontWeight: '700', color: neutral[900], flexShrink: 1 },
  bookmark: { fontSize: 16 },
  meta: { fontSize: 12, color: neutral[500], marginTop: 2 },
  statusOpen: { fontSize: 12, fontWeight: '600', color: brand.mint },
  statusClosed: { fontSize: 12, fontWeight: '600', color: brand.coral },
  tagRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 6, marginTop: spacing[2], alignItems: 'center' },
  score: { fontSize: 11, fontWeight: '700', color: brand.coral },
  empty: { alignItems: 'center', paddingVertical: spacing[8], paddingHorizontal: spacing[5] },
  emptyEmoji: { fontSize: 36, marginBottom: spacing[3] },
  emptyTitle: { fontSize: 15, fontWeight: '700', color: neutral[900] },
  emptyHint: { fontSize: 13, color: neutral[500], marginTop: 4, textAlign: 'center', lineHeight: 19 },
  addNewBtn: { marginTop: spacing[4], alignSelf: 'stretch' },
})
