import { StyleSheet } from 'react-native-unistyles'

import { colors, fill, glassFx, overlay, radius, spacing, type } from '@/shared/ui/tokens'

const { neutral } = colors

export const styles = StyleSheet.create(theme => ({
  searchRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing[2],
    paddingHorizontal: spacing[5],
    marginBottom: spacing[3],
  },
  input: {
    ...type.bodySmall,
    flex: 1,
    height: 48,
    borderRadius: radius.compact,
    backgroundColor: glassFx.chip,
    borderWidth: 1,
    borderColor: neutral[100],
    paddingHorizontal: spacing[4],
    color: neutral[900],
  },
  filterRow: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing[2], paddingHorizontal: spacing[5], paddingBottom: spacing[2] },
  filterToggle: {
    width: 48,
    height: 48,
    borderRadius: radius.compact,
    backgroundColor: glassFx.chip,
    borderWidth: 1,
    borderColor: neutral[100],
    alignItems: 'center',
    justifyContent: 'center',
  },
  filterToggleActive: { borderColor: theme.accent.primary },
  filterCountBadge: {
    position: 'absolute',
    top: -4,
    right: -4,
    minWidth: 18,
    height: 18,
    borderRadius: 9,
    backgroundColor: theme.accent.primary,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 4,
  },
  fab: {
    position: 'absolute',
    right: spacing[5],
    width: 56,
    height: 56,
    borderRadius: 28,
    backgroundColor: theme.accent.primary,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: theme.accent.primary,
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.35,
    shadowRadius: 20,
    elevation: 8,
  },
  sheetInput: {
    ...type.bodySmall,
    height: 46,
    borderRadius: radius.compact,
    backgroundColor: neutral[50],
    borderWidth: 1,
    borderColor: neutral[100],
    paddingHorizontal: spacing[4],
    color: neutral[900],
  },
  priceRow: { flexDirection: 'row', alignItems: 'center', gap: spacing[2] },
  priceInput: { flex: 1 },
  modalRoot: { flex: 1, justifyContent: 'flex-end' },
  backdrop: { ...fill, backgroundColor: overlay.backdrop },
  sheet: {
    backgroundColor: glassFx.sheet,
    borderTopLeftRadius: radius.sheet,
    borderTopRightRadius: radius.sheet,
    paddingHorizontal: spacing[5],
    paddingTop: spacing[5],
  },
  handle: {
    width: 40,
    height: 4,
    borderRadius: 2,
    backgroundColor: neutral[100],
    alignSelf: 'center',
    marginBottom: spacing[4],
  },
  sheetTitle: { marginBottom: spacing[2] },
  sheetSection: { marginTop: spacing[3], marginBottom: spacing[2] },
  sheetOptionRow: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing[2] },
  sheetOption: {
    paddingHorizontal: 12,
    paddingVertical: 9,
    borderRadius: radius.compact,
    backgroundColor: neutral[50],
  },
  sheetOptionActive: { backgroundColor: theme.accent.primary },
  sheetOptionLabel: { ...type.label, color: neutral[700] },
  sheetOptionLabelActive: { color: neutral[0] },
  sheetApply: { marginTop: spacing[5] },
  sheetClear: { alignItems: 'center', paddingVertical: spacing[3] },
  filterBtn: {
    paddingHorizontal: spacing[4],
    paddingVertical: 8,
    borderRadius: radius.compact,
    backgroundColor: glassFx.chip,
    borderWidth: 1,
    borderColor: neutral[100],
  },
  filterBtnActive: { backgroundColor: neutral[900], borderColor: neutral[900] },
  filterLabel: { ...type.label, color: neutral[500] },
  filterLabelActive: { color: neutral[0] },
  card: { flexDirection: 'row', overflow: 'hidden', marginBottom: spacing[3] },
  thumb: { width: 96, alignSelf: 'stretch', minHeight: 96 },
  cardBody: { flex: 1, padding: spacing[3] },
  cardHeader: { flexDirection: 'row', alignItems: 'flex-start', justifyContent: 'space-between', gap: spacing[2] },
  title: { ...type.label, color: neutral[900], flexShrink: 1 },
  bookmark: { ...type.body },
  meta: { ...type.caption, color: neutral[500], marginTop: 2 },
  tagRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 6, marginTop: spacing[2], alignItems: 'center' },
  score: { ...type.label, color: theme.accent.primary },
  empty: { alignItems: 'center', paddingVertical: spacing[8], paddingHorizontal: spacing[5] },
  emptyEmoji: { marginBottom: spacing[3] },
  emptyHint: { marginTop: 4, textAlign: 'center' },
  addNewBtn: { marginTop: spacing[4], alignSelf: 'stretch' },
  sheetHint: { marginBottom: spacing[2] },
}))
