import { StyleSheet } from 'react-native'

import { colors, radius, spacing, type } from '@/shared/ui/tokens'

const { brand, neutral } = colors

export const styles = StyleSheet.create({
  title: { ...type.display, color: neutral[900], marginTop: spacing[2] },
  body: { ...type.body, color: neutral[500], marginTop: spacing[2], marginBottom: spacing[6] },
  input: {
    ...type.bodySmall,
    height: 52,
    borderRadius: radius.compact,
    backgroundColor: neutral[50],
    borderWidth: 1,
    borderColor: neutral[100],
    paddingHorizontal: spacing[4],
    color: neutral[900],
    marginBottom: spacing[2],
  },
  inputError: { borderColor: brand.red },
  errorLabel: { ...type.bodySmall, color: brand.red, marginBottom: spacing[2] },
  verifyBtn: { marginTop: spacing[2] },
  verifyingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing[3],
    paddingVertical: spacing[5],
  },
  verifyingLabel: { ...type.bodySmall, fontWeight: '500', color: neutral[500] },
  resultCard: { overflow: 'hidden', marginTop: spacing[5] },
  resultImage: { width: '100%', height: 140 },
  resultBody: { padding: spacing[4] },
  verifiedBadge: {
    alignSelf: 'flex-start',
    backgroundColor: brand.mintSoft,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: radius.pill,
    marginBottom: spacing[2],
  },
  verifiedBadgeLabel: { ...type.label, fontWeight: '700', color: brand.mint },
  placeName: { ...type.title2, fontWeight: '800', color: neutral[900] },
  placeAddress: { ...type.bodySmall, color: neutral[500], marginTop: 2 },
  placeReviews: { ...type.label, color: neutral[700], marginTop: spacing[2] },
  addBtn: { marginTop: spacing[4] },
  addedLabel: {
    ...type.body,
    textAlign: 'center',
    fontWeight: '600',
    color: brand.mint,
    paddingVertical: spacing[4],
  },
  rejectedCard: {
    marginTop: spacing[5],
    backgroundColor: brand.redSoft,
    borderRadius: radius.card,
    padding: spacing[5],
  },
  rejectedTitle: { ...type.body, fontWeight: '700', color: brand.red },
  rejectedReason: { ...type.bodySmall, color: neutral[700], marginTop: spacing[2] },
  tryAgain: { alignItems: 'center', paddingVertical: spacing[3], marginTop: spacing[2] },
  tryAgainLabel: { ...type.bodySmall, fontWeight: '600', color: neutral[500] },
  warning: { ...type.bodySmall, color: brand.amber, marginTop: spacing[2] },
  attribution: { ...type.caption, color: neutral[500], marginTop: spacing[2] },
  candidateTitle: { ...type.bodySmall, fontWeight: '600', color: neutral[900], marginBottom: spacing[3] },
  candidateRow: {
    paddingVertical: spacing[3],
    paddingHorizontal: spacing[4],
    borderRadius: radius.card,
    borderWidth: 1,
    borderColor: neutral[100],
    marginBottom: spacing[2],
  },
  candidateRowActive: { borderColor: brand.coral, backgroundColor: brand.coralGhost },
  candidateName: { ...type.body, fontWeight: '700', color: neutral[900] },
  candidateAddress: { ...type.bodySmall, color: neutral[500], marginTop: 2 },
  metaSection: { marginTop: spacing[4], gap: spacing[2] },
  metaTitle: { ...type.bodySmall, fontWeight: '700', color: neutral[900] },
  metaLabel: { ...type.label, color: neutral[700], marginTop: spacing[2] },
  chipRow: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing[2] },
  chip: {
    paddingHorizontal: spacing[3],
    paddingVertical: spacing[2],
    borderRadius: radius.pill,
    backgroundColor: neutral[100],
  },
  chipActive: { backgroundColor: brand.coral },
  chipLabel: { ...type.bodySmall, color: neutral[700] },
  chipLabelActive: { color: neutral[0], fontWeight: '600' },
  priceRow: { flexDirection: 'row', gap: spacing[2] },
  priceInput: { flex: 1 },
  noteInput: { minHeight: 72, textAlignVertical: 'top', paddingTop: spacing[3] },
  submissionStatus: { ...type.bodySmall, color: neutral[500], marginTop: spacing[2] },
})
