import { StyleSheet } from 'react-native-unistyles'

import { colors, radius, spacing, type } from '@/shared/ui/tokens'

const { brand, neutral } = colors

export const styles = StyleSheet.create(theme => ({
  title: { marginTop: spacing[2] },
  body: { marginTop: spacing[2], marginBottom: spacing[6] },
  input: {
    ...type.bodySmall,
    height: 52,
    borderRadius: radius.compact,
    backgroundColor: neutral[50],
    borderWidth: 1,
    borderColor: neutral[100],
    paddingHorizontal: spacing[4],
    color: neutral[900],
    marginBottom: spacing[2],
  },
  inputError: { borderColor: brand.red },
  errorLabel: { marginBottom: spacing[2] },
  verifyBtn: { marginTop: spacing[2] },
  verifyingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: spacing[3],
    paddingVertical: spacing[5],
  },
  resultCard: { overflow: 'hidden', marginTop: spacing[5] },
  resultImage: { width: '100%', height: 140 },
  resultBody: { padding: spacing[4] },
  verifiedBadge: {
    alignSelf: 'flex-start',
    backgroundColor: brand.mintSoft,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: radius.pill,
    marginBottom: spacing[2],
  },
  placeAddress: { marginTop: 2 },
  placeReviews: { marginTop: spacing[2] },
  addBtn: { marginTop: spacing[4] },
  addedLabel: {
    textAlign: 'center',
    paddingVertical: spacing[4],
  },
  rejectedCard: {
    marginTop: spacing[5],
    backgroundColor: brand.redSoft,
    borderRadius: radius.card,
    padding: spacing[5],
  },
  rejectedReason: { marginTop: spacing[2] },
  tryAgain: { alignItems: 'center', paddingVertical: spacing[3], marginTop: spacing[2] },
  warning: { marginTop: spacing[2] },
  attribution: { marginTop: spacing[2] },
  candidateTitle: { marginBottom: spacing[3] },
  candidateRow: {
    paddingVertical: spacing[3],
    paddingHorizontal: spacing[4],
    borderRadius: radius.card,
    borderWidth: 1,
    borderColor: neutral[100],
    marginBottom: spacing[2],
  },
  candidateRowActive: { borderColor: theme.accent.primary, backgroundColor: theme.accent.soft },
  candidateAddress: { marginTop: 2 },
  metaSection: { marginTop: spacing[4], gap: spacing[2] },
  metaLabel: { marginTop: spacing[2] },
  chipRow: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing[2] },
  chip: {
    paddingHorizontal: spacing[3],
    paddingVertical: spacing[2],
    borderRadius: radius.pill,
    backgroundColor: neutral[100],
  },
  chipActive: { backgroundColor: theme.accent.primary },
  priceRow: { flexDirection: 'row', gap: spacing[2] },
  priceInput: { flex: 1 },
  noteInput: { minHeight: 72, textAlignVertical: 'top', paddingTop: spacing[3] },
  submissionStatus: { marginTop: spacing[2] },
}))
