import { StyleSheet } from 'react-native'
import { colors, radius, spacing, glassFx, mapColors, shadows } from '@/shared/ui/tokens'

const { brand, neutral } = colors

export const styles = StyleSheet.create({
  header: { paddingHorizontal: spacing[5], paddingVertical: spacing[3] },
  headerRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  addPlaceBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: brand.coral,
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 'auto',
    marginRight: spacing[2],
  },
  addPlaceLabel: { fontSize: 20, fontWeight: '700', color: neutral[0], lineHeight: 24 },
  title: { fontSize: 24, fontWeight: '800', color: neutral[900] },
  toggle: { flexDirection: 'row', backgroundColor: neutral[100], borderRadius: 12, padding: 2 },
  toggleBtn: { paddingHorizontal: 12, height: 32, borderRadius: 10, alignItems: 'center', justifyContent: 'center' },
  toggleBtnActive: { backgroundColor: glassFx.solid },
  toggleLabel: { fontSize: 12, fontWeight: '600', color: neutral[500] },
  toggleLabelActive: { color: neutral[900] },
  filterRow: { flexDirection: 'row', gap: spacing[2], marginTop: spacing[3] },
  filterBtn: {
    paddingHorizontal: spacing[4],
    paddingVertical: 8,
    borderRadius: radius.compact,
    backgroundColor: glassFx.chip,
    borderWidth: 1,
    borderColor: neutral[100],
  },
  filterBtnActive: { backgroundColor: neutral[900], borderColor: neutral[900] },
  filterLabel: { fontSize: 13, fontWeight: '600', color: neutral[500] },
  filterLabelActive: { color: neutral[0] },
  grid: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing[3] },
  gridCard: { width: '48%', overflow: 'hidden' },
  gridThumbWrap: { height: 112 },
  score: {
    position: 'absolute',
    top: 8,
    right: 8,
    backgroundColor: glassFx.pill,
    paddingHorizontal: 6,
    paddingVertical: 2,
    borderRadius: radius.pill,
  },
  scoreLabel: { fontSize: 11, fontWeight: '700', color: brand.coral },
  gridTitle: { fontSize: 13, fontWeight: '700', color: neutral[900] },
  gridMeta: { fontSize: 11, color: neutral[500], marginTop: 2 },
  // Map mock
  mapRoot: { flex: 1, overflow: 'hidden' },
  mapCanvas: { ...StyleSheet.absoluteFillObject, backgroundColor: mapColors.canvas },
  mapUnavailable: { flex: 1, alignItems: 'center', justifyContent: 'center', gap: spacing[3], padding: spacing[5] },
  mapUnavailableLabel: { fontSize: 14, color: neutral[500], textAlign: 'center' },
  searchArea: {
    position: 'absolute',
    top: spacing[3],
    alignSelf: 'center',
    height: 36,
    paddingHorizontal: spacing[4],
    borderRadius: radius.pill,
    backgroundColor: glassFx.solid,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: shadows.warm,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 4,
  },
  searchAreaLabel: { fontSize: 12, fontWeight: '600', color: neutral[900] },
  sheet: {
    position: 'absolute',
    left: spacing[4],
    right: spacing[4],
    flexDirection: 'row',
    overflow: 'hidden',
  },
  sheetThumb: { width: 96 },
  sheetTitle: { fontSize: 14, fontWeight: '700', color: neutral[900], flexShrink: 1 },
  sheetStatusOpen: { fontSize: 12, fontWeight: '600', color: brand.mint },
  sheetStatusClosed: { fontSize: 12, fontWeight: '600', color: brand.coral },
  sheetMeta: { fontSize: 12, color: neutral[500] },
  sheetActions: { flexDirection: 'row', alignItems: 'center', gap: spacing[2], marginTop: spacing[2] },
  sheetBtn: {
    height: 36,
    paddingHorizontal: 12,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: neutral[100],
    alignItems: 'center',
    justifyContent: 'center',
  },
  sheetBtnGrow: { flex: 1 },
  sheetBtnLabel: { fontSize: 12, fontWeight: '600', color: neutral[500] },
  sheetAddBtn: { backgroundColor: brand.coral, borderColor: brand.coral },
  sheetAddDisabled: { backgroundColor: neutral[100], borderColor: neutral[100] },
  sheetAddLabel: { fontSize: 12, fontWeight: '600', color: neutral[0] },
  sheetAddLabelDisabled: { color: neutral[300] },
})
