import { StyleSheet } from 'react-native'
import { colors, radius, spacing, glassFx } from '@/shared/ui/tokens'

const { brand, neutral } = colors

export const styles = StyleSheet.create({
  matchBadge: {
    backgroundColor: brand.mintSoft,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: radius.pill,
  },
  matchBadgeLabel: { fontSize: 12, fontWeight: '700', color: brand.mint },
  timelineIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  legRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing[3],
    marginBottom: spacing[2],
  },
  legLineCol: { width: 40, alignItems: 'center' },
  legLine: { width: 2, height: 18, backgroundColor: neutral[100] },
  legLabel: { fontSize: 12, color: neutral[500], fontWeight: '500' },
  timelineLine: { flex: 1, width: 2, backgroundColor: neutral[100], marginVertical: 4, minHeight: 16 },
  stopCard: { overflow: 'hidden', marginBottom: spacing[3] },
  stopImage: { width: '100%', height: 140 },
  stopHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 4 },
  stopTime: { fontSize: 12, fontWeight: '600', color: brand.coral },
  lockBtn: {
    height: 28,
    paddingHorizontal: 8,
    borderRadius: radius.pill,
    alignItems: 'center',
    justifyContent: 'center',
  },
  stopName: { fontSize: 16, fontWeight: '800', color: neutral[900] },
  stopArea: { fontSize: 13, color: neutral[500], marginTop: 2 },
  stopPriceRow: { flexDirection: 'row', alignItems: 'center', gap: 6, marginTop: spacing[2] },
  stopPrice: { fontSize: 13, fontWeight: '600', color: brand.coral },
  stopDuration: { fontSize: 13, color: neutral[500] },
  stopTags: { flexDirection: 'row', flexWrap: 'wrap', gap: 6, marginTop: spacing[2] },
  stopActions: { flexDirection: 'row', gap: spacing[2], marginTop: spacing[3] },
  detailBtn: {
    flex: 1,
    height: 36,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: neutral[100],
    alignItems: 'center',
    justifyContent: 'center',
  },
  detailLabel: { fontSize: 13, fontWeight: '600', color: neutral[500] },
  directionBtn: {
    flex: 1,
    height: 36,
    borderRadius: 12,
    backgroundColor: neutral[50],
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
  },
  directionLabel: { fontSize: 13, fontWeight: '600', color: neutral[900] },
  summaryBar: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: glassFx.bar,
    borderTopWidth: 1,
    borderTopColor: neutral[100],
    paddingHorizontal: spacing[5],
    paddingTop: spacing[3],
  },
  summaryRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: spacing[4],
    marginBottom: spacing[3],
  },
  summaryColMain: { flex: 1, minWidth: 0 },
  summaryCol: { flexShrink: 0 },
  summaryCaption: { fontSize: 11, color: neutral[500] },
  summaryValue: { fontSize: 15, fontWeight: '800', color: neutral[900] },
  summaryUnit: { fontSize: 10, fontWeight: '600', color: neutral[500] },
  summarySecondary: { fontSize: 10, fontWeight: '600', color: neutral[500], flexShrink: 1 },
  summaryOptional: { fontSize: 10, color: neutral[300] },
  goBtn: { alignSelf: 'stretch' },
  staleWarning: { fontSize: 13, color: colors.brand.amber, lineHeight: 19, marginBottom: spacing[3] },
  summaryOverBudget: { fontSize: 12, color: colors.brand.red, marginTop: 2 },
  regenerateBtn: { alignItems: 'center', paddingVertical: spacing[3], marginTop: spacing[2] },
  regenerateLabel: { fontSize: 14, fontWeight: '600', color: colors.neutral[500] },
})
