import { StyleSheet } from 'react-native'
import { colors, radius, spacing, glassFx, touchTarget, type } from '@/shared/ui/tokens'

const { brand, neutral } = colors

export const styles = StyleSheet.create({
  matchBadge: {
    backgroundColor: brand.mintSoft,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: radius.pill,
  },
  matchBadgeLabel: { ...type.caption, fontWeight: '700', color: brand.mint },
  timelineIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  legRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing[3],
    marginBottom: spacing[2],
  },
  legLineCol: { width: 40, alignItems: 'center' },
  legLine: { width: 2, height: 22, backgroundColor: neutral[100] },
  legLabel: { ...type.bodySmall, color: neutral[500] },
  timelineLine: { flex: 1, width: 2, backgroundColor: neutral[100], marginVertical: 4, minHeight: 16 },
  stopCard: { overflow: 'hidden', marginBottom: spacing[3] },
  stopImage: { width: '100%', height: 140 },
  stopHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 4 },
  stopTime: { ...type.title2, color: brand.coral },
  lockBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 4,
    height: 30,
    paddingHorizontal: 10,
    borderRadius: radius.pill,
    justifyContent: 'center',
  },
  lockBtnLabel: { ...type.caption, fontWeight: '700' },
  stopName: { ...type.title2, color: neutral[900] },
  stopArea: { ...type.bodySmall, color: neutral[500], marginTop: 2 },
  stopPriceRow: { flexDirection: 'row', alignItems: 'center', gap: 6, marginTop: spacing[2] },
  stopPrice: { ...type.label, color: neutral[900] },
  stopDuration: { ...type.bodySmall, color: neutral[500] },
  stopTags: { flexDirection: 'row', flexWrap: 'wrap', gap: 6, marginTop: spacing[2] },
  stopActions: { flexDirection: 'row', gap: spacing[2], marginTop: spacing[3] },
  detailBtn: {
    flex: 1,
    height: touchTarget.min,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: neutral[100],
    alignItems: 'center',
    justifyContent: 'center',
  },
  detailLabel: { ...type.label, color: neutral[500] },
  directionBtn: {
    flex: 1,
    height: touchTarget.min,
    borderRadius: 12,
    backgroundColor: neutral[50],
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
  },
  directionLabel: { ...type.label, color: neutral[900] },
  summaryBar: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: glassFx.bar,
    borderTopWidth: 1,
    borderTopColor: neutral[100],
    paddingHorizontal: spacing[5],
    paddingTop: spacing[3],
  },
  summaryRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: spacing[4],
    marginBottom: spacing[3],
  },
  summaryColMain: { flex: 1, minWidth: 0 },
  summaryCol: { flexShrink: 0 },
  summaryCaption: { ...type.caption, color: neutral[500] },
  summaryAmountRow: { flexDirection: 'row', flexWrap: 'wrap', alignItems: 'baseline', gap: spacing[1] },
  summaryValue: { ...type.title2, color: neutral[900] },
  summaryUnit: { ...type.caption, color: neutral[500] },
  summarySecondary: { ...type.caption, color: neutral[500], flexShrink: 1 },
  summaryOptional: { ...type.caption, color: neutral[500] },
  goBtn: { alignSelf: 'stretch' },
  staleWarning: { ...type.bodySmall, color: brand.amber, marginBottom: spacing[3] },
  summaryOverBudget: { ...type.caption, color: brand.red, marginTop: 2 },
  secondaryRow: { flexDirection: 'row', gap: spacing[2], marginTop: spacing[2] },
  regenerateLabel: { ...type.label, color: neutral[500] },

  /**
   * Locked / required / completed must be told apart without colour (spec §20):
   * a locked stop carries a left edge, a padlock and the word, not just a tint.
   */
  stopCardLocked: { borderLeftWidth: 4, borderLeftColor: brand.coral },
  stopCardCompleted: { opacity: 0.75 },
  stopBadges: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  legRail: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  legDistance: { ...type.bodySmall, color: neutral[500] },
  timelineDot: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  timelineDotLocked: { borderWidth: 2, borderColor: brand.coral },
})
