import { StyleSheet } from 'react-native'
import { colors, radius, spacing } from '@/shared/ui/tokens'

const { brand, neutral } = colors

export const styles = StyleSheet.create({
  matchBadge: {
    backgroundColor: brand.mintSoft,
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: radius.pill,
  },
  matchBadgeLabel: { fontSize: 12, fontWeight: '700', color: brand.mint },
  timelineIcon: {
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: 'center',
    justifyContent: 'center',
  },
  timelineLine: { flex: 1, width: 2, backgroundColor: neutral[100], marginVertical: 4, minHeight: 16 },
  stopCard: { overflow: 'hidden', marginBottom: spacing[3] },
  stopImage: { width: '100%', height: 140 },
  stopHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 4 },
  stopTime: { fontSize: 12, fontWeight: '600', color: brand.coral },
  lockBtn: {
    height: 28,
    paddingHorizontal: 8,
    borderRadius: radius.pill,
    alignItems: 'center',
    justifyContent: 'center',
  },
  stopName: { fontSize: 16, fontWeight: '800', color: neutral[900] },
  stopArea: { fontSize: 13, color: neutral[500], marginTop: 2 },
  stopPriceRow: { flexDirection: 'row', alignItems: 'center', gap: 6, marginTop: spacing[2] },
  stopPrice: { fontSize: 13, fontWeight: '600', color: brand.coral },
  stopDuration: { fontSize: 13, color: neutral[500] },
  stopTags: { flexDirection: 'row', flexWrap: 'wrap', gap: 6, marginTop: spacing[2] },
  stopActions: { flexDirection: 'row', gap: spacing[2], marginTop: spacing[3] },
  detailBtn: {
    flex: 1,
    height: 36,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: neutral[100],
    alignItems: 'center',
    justifyContent: 'center',
  },
  detailLabel: { fontSize: 13, fontWeight: '600', color: neutral[500] },
  directionBtn: {
    flex: 1,
    height: 36,
    borderRadius: 12,
    backgroundColor: neutral[50],
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
  },
  directionLabel: { fontSize: 13, fontWeight: '600', color: neutral[900] },
  summaryBar: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: 'rgba(252,251,248,0.97)',
    borderTopWidth: 1,
    borderTopColor: neutral[100],
    paddingHorizontal: spacing[5],
    paddingTop: spacing[4],
    flexDirection: 'row',
    alignItems: 'center',
  },
  summaryCaption: { fontSize: 11, color: neutral[500] },
  summaryValue: { fontSize: 15, fontWeight: '800', color: neutral[900] },
  summaryUnit: { fontSize: 10, fontWeight: '600', color: neutral[500] },
  summarySecondary: { fontSize: 10, fontWeight: '600', color: neutral[500], flexShrink: 1 },
  summaryOptional: { fontSize: 10, color: neutral[300] },
  goBtn: {
    flexShrink: 0,
    marginLeft: spacing[2],
    backgroundColor: brand.coral,
    paddingHorizontal: spacing[6],
    height: 48,
    borderRadius: radius.compact,
    alignItems: 'center',
    justifyContent: 'center',
  },
  goLabel: { fontSize: 15, fontWeight: '700', color: neutral[0] },
})
