import { StyleSheet } from 'react-native'
import { colors, radius, spacing, glassFx, overlay } from '@/shared/ui/tokens'

const { brand, neutral } = colors

export const styles = StyleSheet.create({
  headerImage: { height: 240 },
  imageScrim: { ...StyleSheet.absoluteFillObject, backgroundColor: overlay.scrimLight },
  backBtn: {
    position: 'absolute',
    left: spacing[4],
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: glassFx.pill,
    alignItems: 'center',
    justifyContent: 'center',
  },
  sheet: {
    flex: 1,
    marginTop: -24,
    borderTopLeftRadius: radius.sheet,
    borderTopRightRadius: radius.sheet,
    backgroundColor: glassFx.sheet,
  },
  name: { fontSize: 22, fontWeight: '800', color: neutral[900] },
  meta: { fontSize: 13, color: neutral[500], marginTop: 2 },
  rating: { fontSize: 13, fontWeight: '700', color: neutral[900], marginTop: 6 },
  price: { fontSize: 14, fontWeight: '700', color: brand.coral, marginTop: spacing[2] },
  open: { fontSize: 13, fontWeight: '600', color: brand.mint, marginTop: 2 },
  addressCard: {
    marginTop: spacing[3],
    backgroundColor: neutral[50],
    borderRadius: radius.compact,
    padding: spacing[3],
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing[3],
  },
  addressIcon: {
    width: 48,
    height: 48,
    borderRadius: 12,
    backgroundColor: brand.mintSoft,
    alignItems: 'center',
    justifyContent: 'center',
  },
  addressLabel: { fontSize: 13, color: neutral[500], flex: 1 },
  sectionTitle: { fontSize: 14, fontWeight: '700', color: neutral[900], marginTop: spacing[4], marginBottom: spacing[2] },
  tagRow: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing[2] },
  ratingsCard: {
    backgroundColor: neutral[50],
    borderRadius: radius.card,
    padding: spacing[4],
    marginTop: spacing[4],
  },
  ratingsTitle: { fontSize: 14, fontWeight: '700', color: neutral[900], marginBottom: spacing[3] },
  ratingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 6,
  },
  ratingLabel: { fontSize: 13, color: neutral[500] },
  ratingTrack: { width: 80, height: 6, borderRadius: 3, backgroundColor: neutral[100], overflow: 'hidden' },
  ratingFill: { height: '100%', backgroundColor: brand.coral, borderRadius: 3 },
  ratingValue: { fontSize: 12, fontWeight: '700', color: neutral[900], width: 26 },
  factsGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing[2], marginTop: spacing[4] },
  factCard: {
    width: '48%',
    borderRadius: radius.compact,
    padding: spacing[3],
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing[2],
  },
  factLabel: { fontSize: 13, color: neutral[500], flexShrink: 1 },
  createFromPlace: {
    height: 48,
    borderRadius: radius.compact,
    backgroundColor: brand.lavenderSoft,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: spacing[4],
  },
  createFromPlaceLabel: { fontSize: 14, fontWeight: '700', color: brand.lavender },
  freshnessRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderTopWidth: 1,
    borderTopColor: neutral[100],
    paddingTop: spacing[3],
    marginTop: spacing[4],
  },
  updated: { fontSize: 12, color: neutral[300] },
  report: { fontSize: 12, fontWeight: '600', color: neutral[500], textDecorationLine: 'underline' },
  actionBar: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
    backgroundColor: glassFx.bar,
    borderTopWidth: 1,
    borderTopColor: neutral[100],
    paddingHorizontal: spacing[5],
    paddingTop: spacing[4],
    flexDirection: 'row',
    gap: spacing[2],
  },
  saveBtn: {
    width: 48,
    height: 48,
    borderRadius: radius.compact,
    borderWidth: 1,
    borderColor: neutral[100],
    alignItems: 'center',
    justifyContent: 'center',
  },
  addBtn: {
    flex: 1,
    height: 48,
    borderRadius: radius.compact,
    borderWidth: 1,
    borderColor: neutral[100],
    alignItems: 'center',
    justifyContent: 'center',
  },
  addLabel: { fontSize: 14, fontWeight: '600', color: neutral[900] },
  dirBtn: {
    flex: 1,
    height: 48,
    borderRadius: radius.compact,
    backgroundColor: brand.coral,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  dirLabel: { fontSize: 14, fontWeight: '600', color: neutral[0] },
})
