import { StyleSheet } from 'react-native'
import { colors, radius, spacing } from '@/shared/ui/tokens'

const { brand, neutral } = colors

export const styles = StyleSheet.create({
  topBar: {
    paddingHorizontal: spacing[5],
    paddingVertical: spacing[3],
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  live: { fontSize: 12, fontWeight: '600', color: brand.coral },
  stopCounter: { fontSize: 18, fontWeight: '800', color: neutral[900] },
  stepDots: { flexDirection: 'row', gap: 4 },
  stepDot: { height: 6, width: 12, borderRadius: 3, backgroundColor: neutral[100] },
  stepDotActive: { width: 20, backgroundColor: brand.coral },
  stepDotDone: { backgroundColor: brand.mint },
  card: { overflow: 'hidden', marginBottom: spacing[4] },
  cardImage: { width: '100%', height: 180 },
  cardBody: { padding: spacing[4] },
  cardHeader: { flexDirection: 'row', alignItems: 'center', gap: spacing[2], marginBottom: 4 },
  name: { fontSize: 20, fontWeight: '800', color: neutral[900] },
  area: { fontSize: 14, color: neutral[500], marginTop: 4 },
  mapThumb: {
    marginTop: spacing[3],
    height: 80,
    borderRadius: radius.compact,
    backgroundColor: brand.mintSoft,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: spacing[2],
  },
  actions: { flexDirection: 'row', gap: spacing[2], marginTop: spacing[3] },
  dirBtn: {
    flex: 1,
    height: 44,
    borderRadius: 12,
    backgroundColor: neutral[50],
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 4,
  },
  dirLabel: { fontSize: 14, fontWeight: '600', color: neutral[900] },
  doneBtn: {
    flex: 1,
    height: 44,
    borderRadius: 12,
    backgroundColor: brand.coral,
    alignItems: 'center',
    justifyContent: 'center',
  },
  doneLabel: { fontSize: 14, fontWeight: '600', color: neutral[0] },
  nextCard: {
    padding: spacing[4],
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing[3],
  },
  nextCaption: { fontSize: 11, fontWeight: '500', color: neutral[500] },
  nextName: { fontSize: 14, fontWeight: '700', color: neutral[900] },
  nextMeta: { fontSize: 12, color: neutral[500] },
})
