import { StyleSheet } from 'react-native'

import { colors, glassFx, glyph, overlay, radius, spacing, type } from '@/shared/ui/tokens'

const { brand, neutral } = colors

export const styles = StyleSheet.create({
  modalRoot: { flex: 1, justifyContent: 'flex-end' },
  backdrop: { ...StyleSheet.absoluteFillObject, backgroundColor: overlay.backdrop },
  sheet: {
    backgroundColor: glassFx.sheet,
    borderTopLeftRadius: radius.sheet,
    borderTopRightRadius: radius.sheet,
    paddingHorizontal: spacing[5],
    paddingTop: spacing[5],
  },
  handle: {
    width: 40,
    height: 4,
    borderRadius: 2,
    backgroundColor: neutral[100],
    alignSelf: 'center',
    marginBottom: spacing[4],
  },
  headerRow: { flexDirection: 'row', alignItems: 'center', gap: spacing[3], marginBottom: spacing[4] },
  headerEmoji: { fontSize: glyph.md },
  title: { ...type.title2, fontWeight: '800', color: neutral[900] },
  stopName: { ...type.bodySmall, color: neutral[500], marginTop: 2 },
  rateLabel: { ...type.bodySmall, fontWeight: '700', color: neutral[900], marginBottom: spacing[2] },
  starsRow: { flexDirection: 'row', gap: spacing[3], marginBottom: spacing[4] },
  star: { fontSize: glyph.md },
  starDim: { opacity: 0.25 },
  tagRow: { flexDirection: 'row', flexWrap: 'wrap', gap: spacing[2], marginBottom: spacing[4] },
  tagBtn: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: radius.compact,
    backgroundColor: neutral[50],
  },
  tagBtnActive: { backgroundColor: brand.coral },
  tagLabel: { ...type.label, color: neutral[500] },
  tagLabelActive: { color: neutral[0] },
  photoRow: { flexDirection: 'row', gap: spacing[2], marginBottom: spacing[4], alignItems: 'center' },
  photoThumb: { width: 64, height: 64, borderRadius: radius.compact },
  /** Sits over the thumbnail while the presign → PUT round trip is in flight. */
  photoOverlay: {
    position: 'absolute',
    left: 0,
    right: 0,
    top: 0,
    bottom: 0,
    borderRadius: radius.compact,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: overlay.scrim,
  },
  photoFailed: { ...type.title1, color: colors.neutral[0] },
  photoAdd: {
    width: 64,
    height: 64,
    borderRadius: radius.compact,
    borderWidth: 1,
    borderStyle: 'dashed',
    borderColor: neutral[300],
    alignItems: 'center',
    justifyContent: 'center',
  },
  photoAddGlyph: { fontSize: glyph.sm, color: neutral[500], lineHeight: 28 },
  addPhotoBtn: {
    height: 64,
    minWidth: 64,
    paddingHorizontal: spacing[3],
    borderRadius: radius.compact,
    borderWidth: 1,
    borderStyle: 'dashed',
    borderColor: neutral[300],
    alignItems: 'center',
    justifyContent: 'center',
    gap: 2,
  },
  addPhotoLabel: { ...type.label, color: neutral[500], textAlign: 'center' },
  photoCount: { ...type.caption, color: neutral[500] },
  billToggle: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: spacing[4],
    paddingVertical: 12,
    borderRadius: radius.compact,
    backgroundColor: neutral[50],
    borderWidth: 1,
    borderColor: neutral[100],
    marginBottom: spacing[3],
  },
  billToggleOn: { backgroundColor: brand.lavenderSoft, borderColor: brand.lavender },
  billToggleLabel: { ...type.bodySmall, fontWeight: '600', color: neutral[700], flexShrink: 1 },
  billToggleLabelOn: { color: brand.lavender },
  billToggleMark: { ...type.body, fontWeight: '800', color: brand.lavender },
  billBox: { gap: spacing[2], marginBottom: spacing[3] },
  billHint: { ...type.caption, color: neutral[500] },
  billInput: {
    ...type.bodySmall,
    height: 46,
    borderRadius: radius.compact,
    backgroundColor: neutral[50],
    borderWidth: 1,
    borderColor: neutral[100],
    paddingHorizontal: spacing[4],
    color: neutral[900],
  },
  billRow: { flexDirection: 'row', gap: spacing[2] },
  billInputTotal: { flex: 1.6 },
  billInputPeople: { flex: 1 },
  billPeopleHint: { ...type.caption, color: neutral[500] },
  billPerPerson: { ...type.label, fontWeight: '700', color: brand.coral },
  billPhotoBtn: {
    height: 44,
    borderRadius: radius.compact,
    borderWidth: 1,
    borderStyle: 'dashed',
    borderColor: neutral[300],
    alignItems: 'center',
    justifyContent: 'center',
  },
  billPhotoDone: { borderStyle: 'solid', borderColor: brand.mint, backgroundColor: brand.mintSoft },
  billPhotoLabel: { ...type.label, color: neutral[500] },
  billPhotoLabelDone: { color: brand.mint },
  billRequired: { ...type.caption, color: brand.red },
  input: {
    ...type.bodySmall,
    minHeight: 44,
    borderRadius: radius.compact,
    backgroundColor: neutral[50],
    paddingHorizontal: spacing[4],
    paddingVertical: 10,
    color: neutral[900],
    marginBottom: spacing[3],
  },
  /** #278 — a check-in that did not land; the sheet stays open for the retry. */
  saveFailed: { ...type.bodySmall, color: brand.red, marginBottom: spacing[3], textAlign: 'center' },
  saveBtn: { alignSelf: 'stretch' },
  skipBtn: { alignItems: 'center', paddingVertical: spacing[3] },
  skipLabel: { ...type.bodySmall, fontWeight: '500', color: neutral[500] },
  unavailableNote: { ...type.caption, color: colors.neutral[500], marginTop: spacing[3] },
})
